### PR TITLE
Navbar

### LINKED ISSUE #10: Navigation Menu
Makes easy to navigate

- The web application must have a menu at the top.
- The menu must contain a button with the option "Start".

### PR DESCRIPTION
**Pull request by angel23v**
Display Navbar with the requierments

For more info see: https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team4/issues/10

### CODE REVIEW

**Review by juperameza — CHANGES_REQUESTED** [review]
2 things 
You pulled this branch from a current working branch 
That is not something that is recommended
And you are doing a navbar only in the index page
I would suggest using a partial to be able to render this navbar everywhere in the app

**Comment by angel23v** [comment]
I clicked by mistake on a option which said "still in work" something like that and makes me a problem with pendient migrates but I already find the problem I guess because the project works again. And by the things here Im working on them

**Comment by angel23v** [comment]
I clicked by mistake on a option which said "still in work" something like that and makes me a problem with pendient migrates but I already find the problem I guess because the project works again. And the things here Im working on them

**Comment by angel23v** [comment]
I pushed the changes on the correct branch

**Pull request closed without merging**
