### PR TITLE
Pagination

### LINKED ISSUE #34: Pagination of the event list
- The list of events on the listing screen must be paginated, that is, it must be displayed in blocks of X number of events per page.
   - The user must be allowed to navigate between the different pages of the event list.

### PR DESCRIPTION
**Pull request by angel23v**
## Quick Info

Now you can navigate between pages with three events in evereyone

## What does this change?
The form to watch & navigate with the events

## Why are you changing that?
Because the events will be piled up & it was going to be awful to watch that

## How do you manually test this?
Clicking on the pages & see the events show per page

## Screenshots 
uno_public
uno
dos_public
dos

### CODE REVIEW

**Comment by MauricioNC** [comment]
What are the new changes? You have the same changes than in the PR #33

**Comment by angel23v** [comment]
> What are the new changes? You have the same changes than in the PR #33 

The pagination just the numbers as u can see on the images if you click u can navigate in the events  & modify some actions on the EventsController

Maybe shows the changes of the las t PR because it hasn't been merged? I guess

**Review by MauricioNC — APPROVED** [review]

**Comment by MauricioNC** [comment]
Ok, just merge the changes and update the local repo before to start a new PR

**Review by juperameza — APPROVED** [review]

**Comment by angel23v** [comment]
Should I push a new commit for the tests? Or what`s happening?

**Pull request merged**
